wandb_version: 1

out_dir:
  desc: null
  value: gpt-default-lora
eval_interval:
  desc: null
  value: 5
log_interval:
  desc: null
  value: 1
eval_iters:
  desc: null
  value: 40
eval_only:
  desc: null
  value: false
always_save_checkpoint:
  desc: null
  value: false
init_from:
  desc: null
  value: gpt2-medium
wandb_project:
  desc: null
  value: lora_finetune
dataset:
  desc: null
  value: openwebtext
gradient_accumulation_steps:
  desc: null
  value: 32
batch_size:
  desc: null
  value: 1
block_size:
  desc: null
  value: 1024
n_layer:
  desc: null
  value: 12
n_head:
  desc: null
  value: 12
n_embd:
  desc: null
  value: 768
dropout:
  desc: null
  value: 0.0
bias:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.0005
max_iters:
  desc: null
  value: 50
weight_decay:
  desc: null
  value: 0.1
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.95
grad_clip:
  desc: null
  value: 1.0
decay_lr:
  desc: null
  value: false
warmup_iters:
  desc: null
  value: 2000
lr_decay_iters:
  desc: null
  value: 600000
min_lr:
  desc: null
  value: 5.0e-09
backend:
  desc: null
  value: nccl
device:
  desc: null
  value: cuda
dtype:
  desc: null
  value: float16
compile:
  desc: null
  value: false
lora_rank:
  desc: null
  value: 64
lora_alpha:
  desc: null
  value: 512
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709397891.047564
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.3
      5: 0.16.3
      6: 4.38.2
      8:
      - 3
      - 5
      13: windows-amd64
